import { Container, Header } from "@/shared/components/shared";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Next Pizza | Корзина",
    description: "Generated by create next app",
};

export default function CheckoutLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Suspense>
            <main className="min-h-screen bg-[#F4F1EE]">
                <Container>
                    <Header
                        className="border-gray-200"
                        hasSearch={false}
                        hasCart={false}
                    />
                    {children}
                </Container>
            </main>
        </Suspense>
    );
}
